### PR TITLE
fix build error "private field 'loop_' is not used"

### PR DESCRIPTION
**Pull request by whsimic**

### CODE REVIEW

**Comment by chenshuo** [comment]
Which compiler/version gives this warning?

**Comment by whsimic** [comment]
my complier is clang, its version is 3.5.0, here is my step:

1. git clone https://github.com/chenshuo/muduo

2. clang++ -v
    
        Ubuntu clang version 3.5.0-4ubuntu2~trusty2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        其他输出略

3. cd muduo

4. patch < clang.diff
5. 
        patching file CMakeLists.txt
        Hunk #1 succeeded at 18 (offset 2 lines).
        Hunk #2 succeeded at 28 (offset 2 lines).

5. ./build.sh -j2

        + pwd
        + SOURCE_DIR=/home/simic/muduo
        + BUILD_DIR=../build
        + BUILD_TYPE=release
        + INSTALL_DIR=../release-install
        + BUILD_NO_EXAMPLES=0
        + mkdir -p ../build/release
        + cd ../build/release
        + cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=../release-install -DCMAKE_BUILD_NO_EXAMPLES=0 /home/simic/muduo
        -- The C compiler identification is Clang 3.5.0
        -- The CXX compiler identification is Clang 3.5.0
        -- Check for working C compiler: /usr/bin/cc
        -- Check for working C compiler: /usr/bin/cc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working CXX compiler: /usr/bin/c++
        -- Check for working CXX compiler: /usr/bin/c++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Boost version: 1.54.0
        -- Looking for include file pthread.h
        -- Looking for include file pthread.h - found
        -- Looking for pthread_create
        -- Looking for pthread_create - not found
        -- Looking for pthread_create in pthreads
        -- Looking for pthread_create in pthreads - not found
        -- Looking for pthread_create in pthread
        -- Looking for pthread_create in pthread - found
        -- Found Threads: TRUE  
        -- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
        -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.35.0") 
        -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
        -- found cares
        -- found curl
        -- found protobuf
        -- found zlib
        -- CXX_FLAGS = -g -DCHECK_PTHREAD_RETURN_VALUE -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Werror -Wconversion -Wno-sign-conversion -Wno-unused-parameter -Wold-style-cast -
        Woverloaded-virtual -Wpointer-arith -Wshadow -Wwrite-strings -march=native -O2 -DNDEBUG
        -- Looking for accept4
        -- Looking for accept4 - found
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /home/simic/build/release
        + make -j2
        Scanning dependencies of target muduo_base_cpp11
        Scanning dependencies of target muduo_base
        [  1%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o
    
        中间输出信息略去
    
        [ 88%] Building CXX object examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer.dir/balancer.cc.o
        Linking CXX executable ../../../bin/protobuf_rpc_sudoku_server
        [ 88%] Built target protobuf_rpc_sudoku_server
        Scanning dependencies of target protobuf_rpc_balancer_raw
        [ 89%] Building CXX object examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer_raw.dir/balancer_raw.cc.o
        /home/simic/muduo/examples/protobuf/rpcbalancer/balancer.cc:205:14: error: private field 'loop_' is not used
        [-Werror,-Wunused-private-field]
        EventLoop* loop_;
        ^
        1 error generated.
        make[2]: *** [examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer.dir/balancer.cc.o] Error 1
        make[1]: *** [examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer.dir/all] Error 2
        make[1]: *** Waiting for unfinished jobs....
        /home/simic/muduo/examples/protobuf/rpcbalancer/balancer_raw.cc:315:14: error: private field 'loop_' is not used
        [-Werror,-Wunused-private-field]
        EventLoop* loop_;
        ^
        1 error generated.
        make[2]: *** [examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer_raw.dir/balancer_raw.cc.o] Error 1
        make[1]: *** [examples/protobuf/rpcbalancer/CMakeFiles/protobuf_rpc_balancer_raw.dir/all] Error 2
        make: *** [all] Error 2

**Comment by whsimic** [comment]
PS：in my comment, /usr/bin/c++ is a link to clang++

simic@kof:~/muduo$ ls -al /usr/bin/c++

    lrwxrwxrwx 1 root root 22 Dec  6 19:21 /usr/bin/c++ -> /usr/local/bin/clang++

**Comment by whsimic** [comment]
misoperation for close this pull request, reopen it

**Comment by chenshuo** [comment]
then you should update clang.diff, not muduo code.

**Pull request closed without merging**
