### PR TITLE
Add udp protocol support

### PR DESCRIPTION
**Pull request by weizili**
Thanks for your great work of writing this network library.
 
We use muduo to build a TCP and UDP service about 2 years ago. This service has been deployed in the production environment which processes about 210 million request per day and it has been running very well over 2 years long.

I hate to merge the code of your master trunk every time, so I propose this PR to reduce my code merging work and share a new feature or example usage of muduo.

This PR implement a nonblocking UDP server. The UDP server has one thread for listening at an UDP port which receives UDP message and dispatches the UDP messages to an working threads pool.

Please check it. If you have any comments, please let me know. Thanks.

### CODE REVIEW

**Comment by chenshuo** [comment]
I don't think this is the right way to support UDP in muduo.

Programming UDP is significantly different than TCP:
1. multiple threads can safely read/write to same UDP socket. so UdpServer no need to read and forward message to thread pool, each thread can read the same UDP socket directly.
2. one UDP 'server' socket can serve multiple clients.
3. one UDP 'client' can send to multiple destination addresses.
4. in fact, a UDP socket can be both client and server.

Overall, I don't think there is an established universal client/server programming model for UDP, that is the reason muduo doesn't support UDP in the first place.

**Comment by weizili** [comment]
我有一些不同的看法。

测试表明：
1. 使用一个udpserver线程阻塞式的接收udp包可以得到最大的收包QPS。因为，如果多线程同时接收，且一边接收一边处理的话，很可能会因为处理慢而导致udp包在系统的网络层被丢弃(缓冲区满了)；这种情况下，如果一个线程接收的话，相当于将包都接收上来了，缓存在应用层(worker线程的队列中)。一般而言，在网络抖动的情况下，会出现udp包突增好几倍，一接收线程、多worker线程模式可以很好的解决这种问题
2. 客户端侧，udp可以不调用connect而直接发包，这没问题。但如果有明确的目标地址，调用connect后再发包，会明显提高性能，大约30%左右增幅。

如上，供大家参考。

**Comment by chenshuo** [comment]
总的来说，我不认为这个PR反映了UDP编程的普遍需求。你可以把它放到 contrib 目录，再把 namespace 改成 contrib 或者别的。

**Comment by weizili** [comment]
OK. 请移步 https://github.com/chenshuo/muduo/pull/203

**Pull request closed without merging**
