### PR TITLE
add millisecond wait for condition

### PR DESCRIPTION
**Pull request by zhuangshi23**

### CODE REVIEW

**Comment by chenshuo** [comment]
Instead of introducing a new function, you may just change the parameter type of waitForSeconds from `int` to `double`.

**Comment by zhuangshi23** [comment]
Technically, yes. But we should **replace** waitForSeconds with waitForMSeconds. The reason:
1. condition wait millisecond make sense than second.
2. second can be expressed by millisecond with integer, and we have to handle double in turn.

**Comment by chenshuo** [comment]
1. why? to me, seconds is far better.
2. what's wrong with double ?

**Comment by zhuangshi23** [comment]
Usually we use condition wait for something like differ thread init, fetch data from remote DB etc, such action cost far less than sec level.  So for ease of use, I suggest use millisecond instead. It lose nothing but more conform to the habit of thinking.

**Comment by chenshuo** [comment]
What is wrong if you write cond.waitForSeconds(0.3) for waiting for 300ms ?

**Comment by zhuangshi23** [comment]
Could you please explain why "seconds is far better"?

**Comment by chenshuo** [comment]
It's the SI main unit for time.

**Comment by zhuangshi23** [comment]
OK, at least, we should change the int to double to be compatible with millisecond requirement; If no comment about this, I will post another PR for this

**Comment by chenshuo** [comment]
Agree.

**Pull request closed without merging**
